---
language: python
python: "2.7"
env:
  - SITE=test1.yml
  - SITE=test2.yml
before_install:
  - sudo apt-get update -qq
install:
  - pip install ansible==1.5.0
script:
  - ansible-playbook -i tests/inventory tests/$SITE --syntax-check
  - ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
